# A string used to distinguish different Supabase projects on the same host name.
project_id = "prism"

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW server_version;` on the remote database to check.
major_version = 15

[db.migrations]
# Specifies an ordered list of schema files to skip in the diff command.
schema_paths = ["./apps/web/supabase/migrations"]
