import { Button } from '@/components/Button'

const roles = [
  {
    title: 'Creators',
    description: 'Install Prism and share in the revenue generated by their attention.',
  },
  {
    title: 'Advertisers',
    description: 'Access a new, premium inventory channel built for the AI era.',
  },
  {
    title: 'Prism',
    description: 'Powers the marketplace, the matching, and the measurement.',
  },
]

export function EconomicsSection() {
  return (
    <section className="section-padding bg-background">
      <div className="container-tight px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mb-16 md:mb-24">
          <p className="eyebrow mb-4">Economics</p>
          <h2 className="text-section mb-6">Everyone wins.</h2>
        </div>

        <div className="grid md:grid-cols-3 gap-8 mb-12">
          {roles.map((role) => (
            <div key={role.title} className="text-center md:text-left">
              <h3 className="text-2xl font-semibold text-foreground mb-4">{role.title}</h3>
              <p className="text-muted-foreground leading-relaxed">{role.description}</p>
            </div>
          ))}
        </div>

        <div className="flex flex-col sm:flex-row gap-4">
          <Button href="/onboarding" size="md">
            Start earning
          </Button>
          <Button href="/advertisers" size="md" variant="outline">
            Start advertising
          </Button>
        </div>
      </div>
    </section>
  )
}
